services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.38.13
    container_name: pre-rag-weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
    restart: unless-stopped
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: "25"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: "node1"

volumes:
  weaviate_data:
